exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('favourites')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('favourites').insert([
        {
          id: 1,
          auth0_id: 'auth0|123456789',
          rating: 5,
          done: 1,
          recipe: {
            recipe: {
              uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_b65931a130aed7b1f69b553111f4f0bc',
              label: 'Baked Potato Snack',
              image:
                'https://edamam-product-images.s3.amazonaws.com/web-img/c03/c03870c0284bdb80902ce95f24187714.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFIaCXVzLWVhc3QtMSJHMEUCIEQlgbDxBmqAcRwHswwtC8dzDcmUCvgK74WJ3su5LxbpAiEA8rkEDkga0%2BZaEqVJEYeBg2liMUvSg1biA2Pf5KFJmDQq1QQI%2Bv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwxODcwMTcxNTA5ODYiDDOkLH90ht6pOFgHnCqpBGiFgZx9ApPyKe9t8xr6XahXcdct9i8DSbV88jXrEqK68f3%2FASJ%2FmjfcGiHWZ9oSNxhNpLy8uWJzCT0ZxazQivze8qx5lhbTppV70BYovGXEOS66A64zSZV1w3oG3gnW3Vd03gZLiNUe154pMLt%2FYiL3m8lT2gmw5%2FNK%2BUtXKn4%2BEGul0Falparrgg0HTHBg5CgWhQ0Bk%2FkQ4icXvd2xlA6gppQDJfAAGzEIR5%2BCdP6xGKvPXf0Kci0baFjzl9d8bzxCrdYLs7f2ZhVauqRt5f303YrXqXfQoEOUyN%2FRW271WzlnoYRStoz92mXC%2BoBHwpuwux8Ez7gEM9rIpoS%2FSXGAARaIQSntPAAlrJ4%2FJi89GrfA5bOgh4l759Mh12cZ1puKUY0FnTOiDO%2F10JnufUZg2FRkqy3twjdgb0RRfzIqAJxvaK6BDnX0gzMQfvr%2FnqyavUnChz5kU2Cu0YfMWGu%2BwNKu9wBQqF8lGt2brh%2Fd7rPWq2NNwp1s8xCaV8blCEpyTWFnZQVJRulLdNFUc%2F2OlKxSALBnYcc062dBbAHT0u3sCw1wr8RoZEm2l%2BYkFPBMitSElIM4EtBkq%2BNsWeJxmVZGeU1dQDn8zHJ%2Bjl1P9OpWrD5L%2FF%2BaIbcZ5%2Ffsq1JJ3CPszBp%2FS3z%2FsbpVrXOaUG%2FpvFGyH%2FpKL%2B9FEI2BG0virV5%2BTNbACHrsUUCEqUroXFcuHKHqcCHEcoUjlABZRsII5LlXM48w%2BpvJmQY6qQGOFw31nn7W97KzTgRGb%2B4XBUPV%2F2se6MHH1IQQ3%2B0%2BohlBsyjYi1y0%2F1FZ6Ryt3slCi0GddI8WhwBcolvcy9yT77vvTweAty7TgyhtGtbLNjs7exhnZnHHbYDGFNCOEhPIg%2BVzrIkNWnzAv%2BuuiO9bx%2FcUBZ2RMF0LX6OxVuvaGqJ9ib7r4w0aR6TbtwOm%2BvjpGDe3UPS7dlo8ngVwmDTYg4TrJWE63OpF&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220927T015756Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFB5H5YXK7%2F20220927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=d1dedf7488c727dbef385dcbc6f6cf8c3ae92fdd101b96f1596603b05088beb5',
              source: 'Martha Stewart',
              url: 'https://www.marthastewart.com/353269/baked-potato-snack',
              shareAs:
                'http://www.edamam.com/recipe/baked-potato-snack-b65931a130aed7b1f69b553111f4f0bc/potato',
              yield: 2,
              dietLabels: ['Low-Fat'],
              healthLabels: [
                'Sugar-Conscious',
                'Vegan',
                'Vegetarian',
                'Pescatarian',
                'Mediterranean',
                'DASH',
                'Dairy-Free',
                'Gluten-Free',
                'Wheat-Free',
                'Egg-Free',
                'Peanut-Free',
                'Tree-Nut-Free',
                'Soy-Free',
                'Fish-Free',
                'Shellfish-Free',
                'Pork-Free',
                'Red-Meat-Free',
                'Crustacean-Free',
                'Celery-Free',
                'Mustard-Free',
                'Sesame-Free',
                'Lupine-Free',
                'Mollusk-Free',
                'Alcohol-Free',
                'No oil added',
                'Sulfite-Free',
                'FODMAP-Free',
                'Kosher',
              ],
              cautions: [],
              ingredientLines: [
                '1 medium sweet potato, or baking potato',
                'Salt and freshly ground black pepper',
              ],
              ingredients: [
                {
                  text: '1 medium sweet potato, or baking potato',
                  quantity: 1,
                  measure: 'potato',
                  food: 'baking potato',
                  weight: 244.95555555555555,
                  foodCategory: 'vegetables',
                  foodId: 'food_brsjy86bq09pzgbmr4ri8bnohrf7',
                  image:
                    'https://www.edamam.com/food-img/71b/71b3756ecfd3d1efa075874377038b67.jpg',
                },
                {
                  text: 'Salt and freshly ground black pepper',
                  quantity: 0,
                  measure: null,
                  food: 'Salt',
                  weight: 1.4697333333333333,
                  foodCategory: 'Condiments and sauces',
                  foodId: 'food_btxz81db72hwbra2pncvebzzzum9',
                  image:
                    'https://www.edamam.com/food-img/694/6943ea510918c6025795e8dc6e6eaaeb.jpg',
                },
                {
                  text: 'Salt and freshly ground black pepper',
                  quantity: 0,
                  measure: null,
                  food: 'black pepper',
                  weight: 0.7348666666666667,
                  foodCategory: 'Condiments and sauces',
                  foodId: 'food_b6ywzluaaxv02wad7s1r9ag4py89',
                  image:
                    'https://www.edamam.com/food-img/c6e/c6e5c3bd8d3bc15175d9766971a4d1b2.jpg',
                },
              ],
              calories: 195.35940422222222,
              totalWeight: 247.13258490336733,
              totalTime: 0,
              cuisineType: ['american'],
              mealType: ['brunch', 'snack'],
              dishType: ['main course'],
              totalNutrients: {
                ENERC_KCAL: {
                  label: 'Energy',
                  quantity: 195.35940422222222,
                  unit: 'kcal',
                },
                FAT: {
                  label: 'Fat',
                  quantity: 0.21992109777777777,
                  unit: 'g',
                },
                FASAT: {
                  label: 'Saturated',
                  quantity: 0.07391778844444444,
                  unit: 'g',
                },
                FATRN: {
                  label: 'Trans',
                  quantity: 0,
                  unit: 'g',
                },
                FAMS: {
                  label: 'Monounsaturated',
                  quantity: 0.010329775777777777,
                  unit: 'g',
                },
                FAPU: {
                  label: 'Polyunsaturated',
                  quantity: 0.1126648582222222,
                  unit: 'g',
                },
                CHOCDF: {
                  label: 'Carbs',
                  quantity: 44.73341612222222,
                  unit: 'g',
                },
                'CHOCDF.net': {
                  label: 'Carbohydrates (net)',
                  quantity: 0,
                  unit: 'g',
                },
                FIBTG: {
                  label: 'Fiber',
                  quantity: 3.3703434888888886,
                  unit: 'g',
                },
                SUGAR: {
                  label: 'Sugars',
                  quantity: 1.523427591111111,
                  unit: 'g',
                },
                'SUGAR.added': {
                  label: 'Sugars, added',
                  quantity: 0,
                  unit: 'g',
                },
                PROCNT: {
                  label: 'Protein',
                  quantity: 5.318401535555556,
                  unit: 'g',
                },
                CHOLE: {
                  label: 'Cholesterol',
                  quantity: 0,
                  unit: 'mg',
                },
                NA: {
                  label: 'Sodium',
                  quantity: 571.3481630693334,
                  unit: 'mg',
                },
                CA: {
                  label: 'Calcium',
                  quantity: 35.445800599030385,
                  unit: 'mg',
                },
                MG: {
                  label: 'Magnesium',
                  quantity: 57.610821404589224,
                  unit: 'mg',
                },
                K: {
                  label: 'Potassium',
                  quantity: 1031.3464176811583,
                  unit: 'mg',
                },
                FE: {
                  label: 'Iron',
                  quantity: 2.18273246795889,
                  unit: 'mg',
                },
                ZN: {
                  label: 'Zinc',
                  quantity: 0.7205581871255896,
                  unit: 'mg',
                },
                P: {
                  label: 'Phosphorus',
                  quantity: 135.8866448888889,
                  unit: 'mg',
                },
                VITA_RAE: {
                  label: 'Vitamin A',
                  quantity: 0.198414,
                  unit: 'µg',
                },
                VITC: {
                  label: 'Vitamin C',
                  quantity: 13.962466666666666,
                  unit: 'mg',
                },
                THIA: {
                  label: 'Thiamin (B1)',
                  quantity: 0.20165721155555555,
                  unit: 'mg',
                },
                RIBF: {
                  label: 'Riboflavin (B2)',
                  quantity: 0.08215809333333333,
                  unit: 'mg',
                },
                NIA: {
                  label: 'Niacin (B3)',
                  quantity: 2.5436895259999996,
                  unit: 'mg',
                },
                VITB6A: {
                  label: 'Vitamin B6',
                  quantity: 0.8472351286666666,
                  unit: 'mg',
                },
                FOLDFE: {
                  label: 'Folate equivalent (total)',
                  quantity: 34.41870511111111,
                  unit: 'µg',
                },
                FOLFD: {
                  label: 'Folate (food)',
                  quantity: 34.41870511111111,
                  unit: 'µg',
                },
                FOLAC: {
                  label: 'Folic acid',
                  quantity: 0,
                  unit: 'µg',
                },
                VITB12: {
                  label: 'Vitamin B12',
                  quantity: 0,
                  unit: 'µg',
                },
                VITD: {
                  label: 'Vitamin D',
                  quantity: 0,
                  unit: 'µg',
                },
                TOCPHA: {
                  label: 'Vitamin E',
                  quantity: 0.03213816888888889,
                  unit: 'mg',
                },
                VITK1: {
                  label: 'Vitamin K',
                  quantity: 5.6121767333333334,
                  unit: 'µg',
                },
                'Sugar.alcohol': {
                  label: 'Sugar alcohol',
                  quantity: 0,
                  unit: 'g',
                },
                WATER: {
                  label: 'Water',
                  quantity: 192.5805242675845,
                  unit: 'g',
                },
              },
              totalDaily: {
                ENERC_KCAL: {
                  label: 'Energy',
                  quantity: 9.76797021111111,
                  unit: '%',
                },
                FAT: {
                  label: 'Fat',
                  quantity: 0.33834015042735044,
                  unit: '%',
                },
                FASAT: {
                  label: 'Saturated',
                  quantity: 0.36958894222222216,
                  unit: '%',
                },
                CHOCDF: {
                  label: 'Carbs',
                  quantity: 14.911138707407408,
                  unit: '%',
                },
                FIBTG: {
                  label: 'Fiber',
                  quantity: 13.481373955555554,
                  unit: '%',
                },
                PROCNT: {
                  label: 'Protein',
                  quantity: 10.636803071111112,
                  unit: '%',
                },
                CHOLE: {
                  label: 'Cholesterol',
                  quantity: 0,
                  unit: '%',
                },
                NA: {
                  label: 'Sodium',
                  quantity: 23.806173461222226,
                  unit: '%',
                },
                CA: {
                  label: 'Calcium',
                  quantity: 3.5445800599030384,
                  unit: '%',
                },
                MG: {
                  label: 'Magnesium',
                  quantity: 13.716862239187911,
                  unit: '%',
                },
                K: {
                  label: 'Potassium',
                  quantity: 21.943540801726773,
                  unit: '%',
                },
                FE: {
                  label: 'Iron',
                  quantity: 12.1262914886605,
                  unit: '%',
                },
                ZN: {
                  label: 'Zinc',
                  quantity: 6.550528973868996,
                  unit: '%',
                },
                P: {
                  label: 'Phosphorus',
                  quantity: 19.41237784126984,
                  unit: '%',
                },
                VITA_RAE: {
                  label: 'Vitamin A',
                  quantity: 0.022046,
                  unit: '%',
                },
                VITC: {
                  label: 'Vitamin C',
                  quantity: 15.513851851851852,
                  unit: '%',
                },
                THIA: {
                  label: 'Thiamin (B1)',
                  quantity: 16.80476762962963,
                  unit: '%',
                },
                RIBF: {
                  label: 'Riboflavin (B2)',
                  quantity: 6.319853333333333,
                  unit: '%',
                },
                NIA: {
                  label: 'Niacin (B3)',
                  quantity: 15.898059537499998,
                  unit: '%',
                },
                VITB6A: {
                  label: 'Vitamin B6',
                  quantity: 65.17193297435897,
                  unit: '%',
                },
                FOLDFE: {
                  label: 'Folate equivalent (total)',
                  quantity: 8.604676277777777,
                  unit: '%',
                },
                VITB12: {
                  label: 'Vitamin B12',
                  quantity: 0,
                  unit: '%',
                },
                VITD: {
                  label: 'Vitamin D',
                  quantity: 0,
                  unit: '%',
                },
                TOCPHA: {
                  label: 'Vitamin E',
                  quantity: 0.21425445925925926,
                  unit: '%',
                },
                VITK1: {
                  label: 'Vitamin K',
                  quantity: 4.6768139444444445,
                  unit: '%',
                },
              },
              digest: [
                {
                  label: 'Fat',
                  tag: 'FAT',
                  schemaOrgTag: 'fatContent',
                  total: 0.21992109777777777,
                  hasRDI: true,
                  daily: 0.33834015042735044,
                  unit: 'g',
                  sub: [
                    {
                      label: 'Saturated',
                      tag: 'FASAT',
                      schemaOrgTag: 'saturatedFatContent',
                      total: 0.07391778844444444,
                      hasRDI: true,
                      daily: 0.36958894222222216,
                      unit: 'g',
                    },
                    {
                      label: 'Trans',
                      tag: 'FATRN',
                      schemaOrgTag: 'transFatContent',
                      total: 0,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                    {
                      label: 'Monounsaturated',
                      tag: 'FAMS',
                      schemaOrgTag: null,
                      total: 0.010329775777777777,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                    {
                      label: 'Polyunsaturated',
                      tag: 'FAPU',
                      schemaOrgTag: null,
                      total: 0.1126648582222222,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                  ],
                },
                {
                  label: 'Carbs',
                  tag: 'CHOCDF',
                  schemaOrgTag: 'carbohydrateContent',
                  total: 44.73341612222222,
                  hasRDI: true,
                  daily: 14.911138707407408,
                  unit: 'g',
                  sub: [
                    {
                      label: 'Carbs (net)',
                      tag: 'CHOCDF.net',
                      schemaOrgTag: null,
                      total: 0,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                    {
                      label: 'Fiber',
                      tag: 'FIBTG',
                      schemaOrgTag: 'fiberContent',
                      total: 3.3703434888888886,
                      hasRDI: true,
                      daily: 13.481373955555554,
                      unit: 'g',
                    },
                    {
                      label: 'Sugars',
                      tag: 'SUGAR',
                      schemaOrgTag: 'sugarContent',
                      total: 1.523427591111111,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                    {
                      label: 'Sugars, added',
                      tag: 'SUGAR.added',
                      schemaOrgTag: null,
                      total: 0,
                      hasRDI: false,
                      daily: 0,
                      unit: 'g',
                    },
                  ],
                },
                {
                  label: 'Protein',
                  tag: 'PROCNT',
                  schemaOrgTag: 'proteinContent',
                  total: 5.318401535555556,
                  hasRDI: true,
                  daily: 10.636803071111112,
                  unit: 'g',
                },
                {
                  label: 'Cholesterol',
                  tag: 'CHOLE',
                  schemaOrgTag: 'cholesterolContent',
                  total: 0,
                  hasRDI: true,
                  daily: 0,
                  unit: 'mg',
                },
                {
                  label: 'Sodium',
                  tag: 'NA',
                  schemaOrgTag: 'sodiumContent',
                  total: 571.3481630693334,
                  hasRDI: true,
                  daily: 23.806173461222226,
                  unit: 'mg',
                },
                {
                  label: 'Calcium',
                  tag: 'CA',
                  schemaOrgTag: null,
                  total: 35.445800599030385,
                  hasRDI: true,
                  daily: 3.5445800599030384,
                  unit: 'mg',
                },
                {
                  label: 'Magnesium',
                  tag: 'MG',
                  schemaOrgTag: null,
                  total: 57.610821404589224,
                  hasRDI: true,
                  daily: 13.716862239187911,
                  unit: 'mg',
                },
                {
                  label: 'Potassium',
                  tag: 'K',
                  schemaOrgTag: null,
                  total: 1031.3464176811583,
                  hasRDI: true,
                  daily: 21.943540801726773,
                  unit: 'mg',
                },
                {
                  label: 'Iron',
                  tag: 'FE',
                  schemaOrgTag: null,
                  total: 2.18273246795889,
                  hasRDI: true,
                  daily: 12.1262914886605,
                  unit: 'mg',
                },
                {
                  label: 'Zinc',
                  tag: 'ZN',
                  schemaOrgTag: null,
                  total: 0.7205581871255896,
                  hasRDI: true,
                  daily: 6.550528973868996,
                  unit: 'mg',
                },
                {
                  label: 'Phosphorus',
                  tag: 'P',
                  schemaOrgTag: null,
                  total: 135.8866448888889,
                  hasRDI: true,
                  daily: 19.41237784126984,
                  unit: 'mg',
                },
                {
                  label: 'Vitamin A',
                  tag: 'VITA_RAE',
                  schemaOrgTag: null,
                  total: 0.198414,
                  hasRDI: true,
                  daily: 0.022046,
                  unit: 'µg',
                },
                {
                  label: 'Vitamin C',
                  tag: 'VITC',
                  schemaOrgTag: null,
                  total: 13.962466666666666,
                  hasRDI: true,
                  daily: 15.513851851851852,
                  unit: 'mg',
                },
                {
                  label: 'Thiamin (B1)',
                  tag: 'THIA',
                  schemaOrgTag: null,
                  total: 0.20165721155555555,
                  hasRDI: true,
                  daily: 16.80476762962963,
                  unit: 'mg',
                },
                {
                  label: 'Riboflavin (B2)',
                  tag: 'RIBF',
                  schemaOrgTag: null,
                  total: 0.08215809333333333,
                  hasRDI: true,
                  daily: 6.319853333333333,
                  unit: 'mg',
                },
                {
                  label: 'Niacin (B3)',
                  tag: 'NIA',
                  schemaOrgTag: null,
                  total: 2.5436895259999996,
                  hasRDI: true,
                  daily: 15.898059537499998,
                  unit: 'mg',
                },
                {
                  label: 'Vitamin B6',
                  tag: 'VITB6A',
                  schemaOrgTag: null,
                  total: 0.8472351286666666,
                  hasRDI: true,
                  daily: 65.17193297435897,
                  unit: 'mg',
                },
                {
                  label: 'Folate equivalent (total)',
                  tag: 'FOLDFE',
                  schemaOrgTag: null,
                  total: 34.41870511111111,
                  hasRDI: true,
                  daily: 8.604676277777777,
                  unit: 'µg',
                },
                {
                  label: 'Folate (food)',
                  tag: 'FOLFD',
                  schemaOrgTag: null,
                  total: 34.41870511111111,
                  hasRDI: false,
                  daily: 0,
                  unit: 'µg',
                },
                {
                  label: 'Folic acid',
                  tag: 'FOLAC',
                  schemaOrgTag: null,
                  total: 0,
                  hasRDI: false,
                  daily: 0,
                  unit: 'µg',
                },
                {
                  label: 'Vitamin B12',
                  tag: 'VITB12',
                  schemaOrgTag: null,
                  total: 0,
                  hasRDI: true,
                  daily: 0,
                  unit: 'µg',
                },
                {
                  label: 'Vitamin D',
                  tag: 'VITD',
                  schemaOrgTag: null,
                  total: 0,
                  hasRDI: true,
                  daily: 0,
                  unit: 'µg',
                },
                {
                  label: 'Vitamin E',
                  tag: 'TOCPHA',
                  schemaOrgTag: null,
                  total: 0.03213816888888889,
                  hasRDI: true,
                  daily: 0.21425445925925926,
                  unit: 'mg',
                },
                {
                  label: 'Vitamin K',
                  tag: 'VITK1',
                  schemaOrgTag: null,
                  total: 5.6121767333333334,
                  hasRDI: true,
                  daily: 4.6768139444444445,
                  unit: 'µg',
                },
                {
                  label: 'Sugar alcohols',
                  tag: 'Sugar.alcohol',
                  schemaOrgTag: null,
                  total: 0,
                  hasRDI: false,
                  daily: 0,
                  unit: 'g',
                },
                {
                  label: 'Water',
                  tag: 'WATER',
                  schemaOrgTag: null,
                  total: 192.5805242675845,
                  hasRDI: false,
                  daily: 0,
                  unit: 'g',
                },
              ],
            },
          },
        },
      ])
    })
}
