exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('produce')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('produce').insert([
        {
          id: 1,
          name: 'apple',
          display_name: 'Apple/Āporo',
          type: 'fruit',
          image_url: '/images/apple.jpg',
        },
        {
          id: 2,
          name: 'apricot',
          display_name: 'Apricot/Aperekoti',
          type: 'fruit',
          image_url: 'images/apricot.jpg',
        },
        {
          id: 3,
          name: 'avocado',
          display_name: 'Avocado/Awakato',
          type: 'fruit',
          image_url: 'images/avocado.jpg',
        },
        {
          id: 4,
          name: 'banana',
          display_name: 'Banana/Panana',
          type: 'fruit',
          image_url: 'images/banana.jpg',
        },
        {
          id: 5,
          name: 'blackberry',
          display_name: 'Blackberry/Parakipere',
          type: 'fruit',
          image_url: '/images/blackberries.jpeg',
        },
        {
          id: 6,
          name: 'blackcurrant',
          display_name: 'Blackcurrants',
          type: 'fruit',
          image_url: '/images/blackcurrants.jpeg',
        },
        {
          id: 7,
          name: 'blueberry',
          display_name: 'Blueberry/Rēua',
          type: 'fruit',
          image_url: 'images/blueberry.jpg',
        },
        {
          id: 8,
          name: 'boysenberry',
          display_name: 'Boysenberries',
          type: 'fruit',
          image_url: 'images/boysenberries.jpeg',
        },
        {
          id: 9,
          name: 'cherry',
          display_name: 'Cherry/Tiere',
          type: 'fruit',
          image_url: 'images/cherry.jpg',
        },
        {
          id: 10,
          name: 'feijoa',
          display_name: 'Feijoa/Whitoa',
          type: 'fruit',
          image_url: 'images/feijoa.jpg',
        },
        {
          id: 11,
          name: 'gooseberry',
          display_name: 'Gooseberry/Kuihipere',
          type: 'fruit',
          image_url: 'images/gooseberries.jpeg',
        },
        {
          id: 12,
          name: 'grapefruit',
          display_name: 'Grapefruit/Huakerepe',
          type: 'fruit',
          image_url: 'images/grapefruit.jpg',
        },
        {
          id: 13,
          name: 'black grapes',
          display_name: 'Grape/Kerepi - Black',
          type: 'fruit',
          image_url: 'images/grapes.jpg',
        },
        {
          id: 14,
          name: 'green grapes',
          display_name: 'Grape/Kerepi - Green',
          type: 'fruit',
          image_url: 'images/grapes-green.jpg',
        },
        {
          id: 15,
          name: 'honeydew melon',
          display_name: 'Honeydew Melon',
          type: 'fruit',
          image_url: 'images/honeydew-melon.png',
        },
        {
          id: 16,
          name: 'kiwiberry',
          display_name: 'Kiwiberries',
          type: 'fruit',
          image_url: 'images/kiwiberries.jpg',
        },
        {
          id: 17,
          name: 'gold kiwifruit',
          display_name: 'Kiwifruit/Huakiwi - Gold',
          type: 'fruit',
          image_url: 'images/gold-kiwifruit.jpg',
        },
        {
          id: 18,
          name: 'green kiwifruit',
          display_name: 'Kiwifruit/Huakiwi - Green',
          type: 'fruit',
          image_url: 'images/kiwifruit.jpg',
        },
        {
          id: 19,
          name: 'lemon',
          display_name: 'Lemon/Rēmana',
          type: 'fruit',
          image_url:
            'https://www.5aday.co.nz/media/77644/lemons.jpg?&width=800&height=400&anchor=top&mode=crop',
        },
        {
          id: 20,
          name: 'lime',
          display_name: 'Lime/Raima',
          type: 'fruit',
          image_url: 'images/limes.jpeg',
        },
        {
          id: 21,
          name: 'mandarin',
          display_name: 'Mandarin/Manarini',
          type: 'fruit',
          image_url: 'images/mandarin.jpeg',
        },
        {
          id: 22,
          name: 'mango',
          display_name: 'Mango',
          type: 'fruit',
          image_url:
            'https://www.5aday.co.nz/media/141458/mango-copy.jpg?&width=800&height=400&anchor=top&mode=crop',
        },
        {
          id: 23,
          name: 'nashi',
          display_name: 'Nashi',
          type: 'fruit',
          image_url: 'images/nashipear.jpg',
        },
        {
          id: 24,
          name: 'nectarine',
          display_name: 'Nectarine/Pītiti kiri',
          type: 'fruit',
          image_url: 'images/nectarine.jpeg',
        },
        {
          id: 25,
          name: 'navel orange',
          display_name: 'Orange/Ārani - Navel',
          type: 'fruit',
          image_url: 'images/orangenavel.jpg',
        },
        {
          id: 26,
          name: 'orange',
          display_name: 'Orange/Ārani - Valencia',
          type: 'fruit',
          image_url: 'images/orange.png',
        },
        {
          id: 27,
          name: 'passionfruit',
          display_name: 'Passionfruit/Kōhia',
          type: 'fruit',
          image_url: 'images/passionfruit.jpg',
        },
        {
          id: 28,
          name: 'peach',
          display_name: 'Peach/Pītiti',
          type: 'fruit',
          image_url: 'images/peaches.jpeg',
        },
        {
          id: 29,
          name: 'pear',
          display_name: 'Pear/Pea',
          type: 'fruit',
          image_url: 'images/pears.jpg',
        },
        {
          id: 30,
          name: 'pineapple',
          display_name: 'Pineapple/Paināporo',
          type: 'fruit',
          image_url: 'images/pineapple.jpg',
        },
        {
          id: 31,
          name: 'plum',
          display_name: 'Plum/Paramu',
          type: 'fruit',
          image_url: 'images/plums.jpg',
        },
        {
          id: 32,
          name: 'raspberry',
          display_name: 'Raspberry/Rāhipere',
          type: 'fruit',
          image_url: 'images/raspberries.jpeg',
        },
        {
          id: 33,
          name: 'redcurrant',
          display_name: 'Redcurrants',
          type: 'fruit',
          image_url: 'images/redcurrants.jpeg',
        },
        {
          id: 34,
          name: 'strawberry',
          display_name: 'Strawberry/Rōpere',
          type: 'fruit',
          image_url: 'images/strawberry.jpg',
        },
        {
          id: 35,
          name: 'tamarillo',
          display_name: 'Tamarillo/Tamariro',
          type: 'fruit',
          image_url: 'images/tamarillo.jpg',
        },
        {
          id: 36,
          name: 'tangelo',
          display_name: 'Tangelo/Tānero',
          type: 'fruit',
          image_url: 'images/tangelo.jpg',
        },
        {
          id: 37,
          name: 'watermelon',
          display_name: 'Watermelon/Waimerengi',
          type: 'fruit',
          image_url: 'images/watermelon.jpg',
        },
        {
          id: 38,
          name: 'rock melon',
          display_name: 'Rock Melon/Rāka merengi',
          type: 'fruit',
          image_url: 'images/rock-melon.png',
        },
        {
          id: 39,
          name: 'globe artichoke',
          display_name: 'Artichoke/Atihoka - Globe',
          type: 'vegetable',
          image_url: 'images/artichoke-globe.jpg',
        },
        {
          id: 40,
          name: 'jerusalem artichoke',
          display_name: 'Artichoke/Atihoka - Jerusalem',
          type: 'vegetable',
          image_url: 'images/artichoke-jerusalem.jpg',
        },
        {
          id: 41,
          name: 'asparagus',
          display_name: 'Asparagus/Apareka',
          type: 'vegetable',
          image_url: 'images/asparagus.jpg',
        },
        {
          id: 42,
          name: 'beans',
          display_name: 'Bean/Pīni',
          type: 'vegetable',
          image_url: 'images/beans.jpg',
        },
        {
          id: 43,
          name: 'beetroot',
          display_name: 'Beetroot/Tāmore whero',
          type: 'vegetable',
          image_url: 'images/beetroot.png',
        },
        {
          id: 44,
          name: 'broccoli',
          display_name: 'Broccoli/Pūpihi',
          type: 'vegetable',
          image_url: 'images/broccoli.jpg',
        },
        {
          id: 45,
          name: 'broccolini',
          display_name: 'Broccolini',
          type: 'vegetable',
          image_url: 'images/broccolini.jpg',
        },
        {
          id: 46,
          name: 'brussel sprouts',
          display_name: 'Brussels sprouts/Aonanī',
          type: 'vegetable',
          image_url: 'images/brussels-sprouts.jpg',
        },
        {
          id: 47,
          name: 'buttercup squash',
          display_name: 'Buttercup Squash',
          type: 'vegetable',
          image_url: 'images/buttercup.jpg',
        },
        {
          id: 48,
          name: 'butternut',
          display_name: 'Butternut',
          type: 'vegetable',
          image_url: 'images/butternut.jpg',
        },
        {
          id: 49,
          name: 'cabbage',
          display_name: 'Cabbage/Kāpeti',
          type: 'vegetable',
          image_url: 'images/cabbage.jpg',
        },
        {
          id: 50,
          name: 'capsicum',
          display_name: 'Capsicum/Rapikama',
          type: 'vegetable',
          image_url: 'images/capsicum.png',
        },
        {
          id: 51,
          name: 'carrot',
          display_name: 'Carrot/Kāroti',
          type: 'vegetable',
          image_url: 'images/carrot.jpg',
        },
        {
          id: 52,
          name: 'cauliflower',
          display_name: 'Cauliflower/Kareparāoa',
          type: 'vegetable',
          image_url: 'images/cauliflower.png',
        },
        {
          id: 53,
          name: 'celery',
          display_name: 'Celery/Herewī',
          type: 'vegetable',
          image_url: 'images/celery.png',
        },
        {
          id: 54,
          name: 'chilli',
          display_name: 'Chilli/Hiri',
          type: 'vegetable',
          image_url: 'images/chilli.jpg',
        },
        {
          id: 55,
          name: 'courgette',
          display_name: 'Courgette/Kamoriki',
          type: 'vegetable',
          image_url: 'images/courgettes.png',
        },
        {
          id: 56,
          name: 'cucumber',
          display_name: 'Cucumber/Kūkama',
          type: 'vegetable',
          image_url: 'images/cucumber.png',
        },
        {
          id: 57,
          name: 'eggplant',
          display_name: 'Eggplant/Otahua',
          type: 'vegetable',
          image_url: 'images/aubergine.png',
        },
        {
          id: 58,
          name: 'fennel',
          display_name: 'Fennel/Huahaunga',
          type: 'vegetable',
          image_url: 'images/fennel.jpg',
        },
        {
          id: 59,
          name: 'fresh herbs',
          display_name: 'Fresh Herbs/Amiami',
          type: 'vegetable',
          image_url: 'images/fresh-herbs.jpg',
        },
        {
          id: 60,
          name: 'garlic',
          display_name: 'Garlic/Kārika',
          type: 'vegetable',
          image_url: 'images/garlic.jpg',
        },
        {
          id: 61,
          name: 'ginger',
          display_name: 'Ginger/Tinitia',
          type: 'vegetable',
          image_url: 'images/ginger.jpg',
        },
        {
          id: 62,
          name: 'kale',
          display_name: 'Kale/Kapekape',
          type: 'vegetable',
          image_url: 'images/kale.jpg',
        },
        {
          id: 63,
          name: 'kohlrabi',
          display_name: 'Kohlrabi/Koapi',
          type: 'vegetable',
          image_url: 'images/kohlrabi.jpg',
        },
        {
          id: 64,
          name: 'kumara',
          display_name: 'Kūmara',
          type: 'vegetable',
          image_url: 'images/kumara.png',
        },
        {
          id: 65,
          name: 'leek',
          display_name: 'Leeks/Rikiroa',
          type: 'vegetable',
          image_url: 'images/leeks.jpg',
        },
        {
          id: 66,
          name: 'lettuce',
          display_name: 'Lettuce/Rētihi',
          type: 'vegetable',
          image_url: 'images/lettuce.png',
        },
        {
          id: 67,
          name: 'mushroom',
          display_name: 'Mushroom/Harore',
          type: 'vegetable',
          image_url: 'images/mushroom.jpg',
        },
        {
          id: 68,
          name: 'onion',
          display_name: 'Onion/Riki',
          type: 'vegetable',
          image_url: 'images/onion.jpg',
        },
        {
          id: 69,
          name: 'parsnip',
          display_name: 'Parsnip/Tāmore mā',
          type: 'vegetable',
          image_url: 'images/parsnip.jpg',
        },
        {
          id: 70,
          name: 'pea',
          display_name: 'Peas/Pī',
          type: 'vegetable',
          image_url: 'images/pea.jpg',
        },
        {
          id: 71,
          name: 'potato',
          display_name: 'Potato/Rīwai',
          type: 'vegetable',
          image_url: 'images/potato.jpg',
        },
        {
          id: 72,
          name: 'pumpkin',
          display_name: 'Pumpkin/Paukena',
          type: 'vegetable',
          image_url: 'images/pumpkin.jpg',
        },
        {
          id: 73,
          name: 'puha',
          display_name: 'Pūhā',
          type: 'vegetable',
          image_url: 'images/puha.jpg',
        },
        {
          id: 74,
          name: 'radish',
          display_name: 'Radish/Rarihi ',
          type: 'vegetable',
          image_url: 'images/radish.jpg',
        },
        {
          id: 75,
          name: 'salad greens',
          display_name: 'Salad Greens',
          type: 'vegetable',
          image_url: 'images/salad-greens.png',
        },
        {
          id: 76,
          name: 'silverbeet',
          display_name: 'Silver Beet/Korare',
          type: 'vegetable',
          image_url: 'images/silverbeet.jpg',
        },
        {
          id: 77,
          name: 'snow peas',
          display_name: 'Snow Peas',
          type: 'vegetable',
          image_url: 'images/snow-pea.jpg',
        },
        {
          id: 78,
          name: 'spinach',
          display_name: 'Spinach/Kōkihi',
          type: 'vegetable',
          image_url: 'images/spinach.jpg',
        },
        {
          id: 79,
          name: 'spring onion',
          display_name: 'Spring Onions/Rikiriki',
          type: 'vegetable',
          image_url: 'images/spring-onion.jpg',
        },
        {
          id: 80,
          name: 'bean sprouts',
          display_name: 'Bean Sprouts',
          type: 'vegetable',
          image_url: 'images/bean-sprouts.jpg',
        },
        {
          id: 81,
          name: 'swede',
          display_name: 'Swede/Tuwīti tānapu',
          type: 'vegetable',
          image_url: 'images/swede.jpg',
        },
        {
          id: 82,
          name: 'corn',
          display_name: 'Sweetcorn/Kānga',
          type: 'vegetable',
          image_url: 'images/corn.jpg',
        },
        {
          id: 83,
          name: 'taewa',
          display_name: 'Taewa',
          type: 'vegetable',
          image_url: 'images/taewa.jpg',
        },
        {
          id: 84,
          name: 'taro',
          display_name: 'Taro',
          type: 'vegetable',
          image_url: 'images/taro.jpg',
        },
        {
          id: 85,
          name: 'tomato',
          display_name: 'Tomato/Tōmato',
          type: 'vegetable',
          image_url: 'images/tomato.jpg',
        },
        {
          id: 86,
          name: 'turnip',
          display_name: 'Turnip/Tōnape',
          type: 'vegetable',
          image_url: 'images/turnip.jpg',
        },
        {
          id: 87,
          name: 'watercress',
          display_name: 'Watercress/Wātakirihi',
          type: 'vegetable',
          image_url: 'images/watercress.jpg',
        },
        {
          id: 88,
          name: 'witloof',
          display_name: 'Witloof',
          type: 'vegetable',
          image_url: 'images/witloof.jpg',
        },
        {
          id: 89,
          name: 'yam',
          display_name: 'Yam/Uwhi',
          type: 'vegetable',
          image_url: 'images/yam.jpg',
        },
        {
          id: 90,
          name: 'rhubarb',
          display_name: 'Rhubarb/Rūpapa',
          type: 'vegetable',
          image_url: 'images/rhubarb.jpg',
        },
        {
          id: 91,
          name: 'persimmon',
          display_name: 'Persimmon/Āporo makimaki',
          type: 'fruit',
          image_url: 'images/persimmon.jpg',
        },
      ])
    })
}
